
from typing import TypedDict, Annotated, List, Dict, Any
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

def add_list_items(left: List[Any], right: List[Any]) -> List[Any]:
    """Adds items from the right list to the left list."""
    if not right:
        return left
    return left + right

class AgentState(TypedDict):
    """
    State of the graph passed between nodes.
    """
    # Chat history
    messages: Annotated[list[BaseMessage], add_messages]
    
    # The multi-step plan generated by the planner
    plan: List[Dict[str, Any]]
    
    # Results from tool executions
    intermediate_results: Annotated[List[Any], add_list_items]
    
    # Index of the current step
    current_step: int
    
    # The original user query
    original_query: str
    
    # The rewritten query after resolving pronouns (Contextualization)
    rewritten_query: str
    
    # The embedding model to use
    model_name: str